### ISSUE TITLE
error in fine tune LLM using axolotl

### ISSUE THREAD

**Issue by OE-LUCIFER** [mlabonne/llm-course#56]
`/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py:432:` FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/content/axolotl/src/axolotl/cli/train.py", line 59, in <module>
    fire.Fire(do_cli)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/dist-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/content/axolotl/src/axolotl/cli/train.py", line 35, in do_cli
    return do_train(parsed_cfg, parsed_cli_args)
  File "/content/axolotl/src/axolotl/cli/train.py", line 55, in do_train
    return train(cfg=cfg, cli_args=cli_args, dataset_meta=dataset_meta)
  File "/content/axolotl/src/axolotl/train.py", line 104, in train
    trainer = setup_trainer(
  File "/content/axolotl/src/axolotl/utils/trainer.py", line 338, in setup_trainer
    return trainer_builder.build(total_num_steps)
  File "/content/axolotl/src/axolotl/core/trainer_builder.py", line 1245, in build
    trainer = trainer_cls(
  File "/content/axolotl/src/axolotl/core/trainer_builder.py", line 223, in __init__
    super().__init__(*_args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 539, in __init__
    self.callback_handler = CallbackHandler(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer_callback.py", line 313, in __init__
    self.add_callback(cb)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer_callback.py", line 330, in add_callback
    cb = callback() if isinstance(callback, type) else callback
  File "/usr/local/lib/python3.10/dist-packages/transformers/integrations/integration_utils.py", line 954, in __init__
    raise RuntimeError("MLflowCallback requires mlflow to be installed. Run `pip install mlflow`.")
RuntimeError: MLflowCallback requires mlflow to be installed. Run `pip install mlflow`.
Exception ignored in: <function MLflowCallback.__del__ at 0x7d8a76cbf400>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/integrations/integration_utils.py", line 1105, in __del__
    self._auto_end_run
AttributeError: 'MLflowCallback' object has no attribute '_auto_end_run'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 46, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1057, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 673, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'axolotl.cli.train', 'config.yaml']' returned non-zero exit status 1.`

**Comment by mlabonne** [comment]
It looks like you want to use mlflow but it isn't installed (not a requirement in Axolotl). I'd recommend you to fork the [lazyaxolotl.sh script](https://gist.github.com/mlabonne/9d85e1bb8fc3efe8649b677845c83bdb) and add "mlflow" in the first "pip3 install". Then, you can copy and paste the URL of your script in the `SCRIPT` field of the LazyAxolotl notebook.

**Comment by OE-LUCIFER** [comment]
> It looks like you want to use mlflow but it isn't installed (not a requirement in Axolotl). I'd recommend you to fork the [lazyaxolotl.sh script](https://gist.github.com/mlabonne/9d85e1bb8fc3efe8649b677845c83bdb) and add "mlflow" in the first "pip3 install". Then, you can copy and paste the URL of your script in the `SCRIPT` field of the LazyAxolotl notebook.

Thanks it worked

**Comment by steveepreston** [comment]
```diff
+ pip install mlflow
```
